#!/bin/zsh

export GOPATH=$HOME/.go
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='green'
DEFAULT_USER=`whoami`
source $HOME/.antigen.zsh

# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundle git
antigen bundle pip
antigen bundle screen
antigen bundle tmux
antigen bundle colored-man-pages
antigen bundle wd
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

# Load the theme
antigen theme bhilburn/powerlevel9k powerlevel9k

# Tell antigen that you're done
antigen apply
