name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: shellcheck
        uses: docker://koalaman/shellcheck-alpine:v0.9.0
        with:
          args: shellcheck setup.sh
