name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck:v0.9.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: shellcheck
        run: |
          shellcheck setup.sh
